### ISSUE TITLE
External monitor freezing

### ISSUE THREAD

**Issue by sriracha666** [pop-os/pop#3085]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
I have a laptop connected to an external monitor (Alienware AW252HF, 240hz monitor). When I have more than one program open, the monitor will freeze completely. I can still use the computer from the laptop's monitor, but I can't move the windows from the monitor to the laptop screen or do anything with the monitor. The only thing I've found that resolves this is turning the monitor on and off again. 

This has most often happened when I play a game (FFXIV usually) and open firefox. When this happens with FFXIV I often have to restart my computer because FFXIV will refuse to load. 

It happened again today when I only had these programs open: firefox, winetricks, file folder viewer. I have a support log zip generated right after I turned off/on my monitor. 

**Steps to reproduce (if you know):**

**Hardware**
             /////////////                gaymerboi666@pop-os 
         /////////////////////            ------------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: ROG Strix G531GV_G531GV 1.0 
   /////76767//7676767//////////////      Kernel: 6.2.6-76060206-generic 
  /////767676///*76767///////////////     Uptime: 5 hours, 8 mins 
 ///////767676///76767.///7676*///////    Packages: 2122 (dpkg), 21 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080, 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-9750H (12) @ 4.500GHz 
    /////767676767676767676767/////       GPU: Intel CoffeeLake-H GT2 [UHD Grap 
      ///////////////////////////         GPU: NVIDIA GeForce RTX 2060 Mobile 
         /////////////////////            Memory: 5484MiB / 15832MiB 
             /////////////

**Comment by yoginho** [comment]
Absolutely same issue here (all identical to the above, except that I am using a Dell Latitude laptop, but the problem seems to occur across a wide range of hardware...). It renders Pop_OS! basically useless for my work, so I'll switch to Ubuntu if this bug isn't fixed with highest priority. It seems that a lot of users are affected by this issue. It was caused by one of the last updates to the system. I've never had it before. Extremely annoying.

**Comment by sonAndrew** [comment]
I have the exact same issue as above. I am using a Alienware m16 R1 laptop. This issue recently started before I installed Pop!_OS on this laptop last week. I have an old 2015 Macbook Pro that I have been using pop on for a few months now and it has the same issue. 

The only way I found to fix it:

1. to unplug the HDMI from the laptop and plug it back in
2.  to change the display position
3. to change the scale

These are only temporary fixes because the issue persists even after doing these things.

I am not sure of the cause but any information or update would be helpful.

Below is the System and Machine and Graphics information for the Alienware machine.
```
System:
  Kernel: 6.4.6-76060406-generic x86_64 bits: 64 compiler: N/A
    Desktop: GNOME 42.5 Distro: Pop!_OS 22.04 LTS base: Ubuntu 22.04 LTS Jammy
Machine:
  Type: Laptop System: Alienware product: Alienware m16 R1 v: N/A
  Mobo: Alienware model: 09R1YM v: A00 
    UEFI: Alienware v: 1.10.1 date: 07/28/2023
Graphics:
  Device-1: Intel vendor: Dell driver: i915 v: kernel bus-ID: 0000:00:02.0
  Device-2: NVIDIA vendor: Dell driver: nvidia v: 535.104.05
    bus-ID: 0000:01:00.0
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1: 1920x1080~75Hz 2: 2560x1600~165Hz
  OpenGL: renderer: Mesa Intel UHD Graphics (ADL-S GT1)
    v: 4.6 Mesa 23.1.3-1pop0~1689084530~22.04~0618746 direct render: Yes
```
