### ISSUE TITLE
npm version mismatch on 19.04

### ISSUE THREAD

**Issue by toxicmender** [pop-os/pop#648]
**Distribution (run `cat /etc/os-release`):**
```sh
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
 ```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```yaml
npm:
  Installed: 5.8.0+ds6-4
  Candidate: 5.8.0+ds6-4
  Version table:
 *** 5.8.0+ds6-4 500
        500 http://us.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu disco/universe i386 Packages
        100 /var/lib/dpkg/status
```
```yaml
nodejs:
  Installed: 10.15.2~dfsg-1
  Candidate: 10.15.2~dfsg-1
  Version table:
 *** 10.15.2~dfsg-1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
Nodejs 10.x series requires npm version higher than what is currently available (>=6.4 afaik).
The warning appears whenever npm is used to install a node module.

**Steps to reproduce (if you know):**
```npm install $MODULE_NAME```

**Expected behavior:**
No version mismatch (cause of warning)

**Other Notes:**
This seems to be an inherited bug from Ubuntu (The version mismatch seems to originate from their package repository)
